version: "3"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth_db 
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product_db 
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432

  sales-db:
    container_name: mongo_db
    image: mongo:5.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo123
    ports:
     - 27017:27017
    volumes:
      - /Users/rvmagno/data/mongo/5:/data/db


  # auth-api:
  #   build: './repos/auth-api'
  #   container_name: auth-api
  #   environment:
  #     - PORT=8080
  #   ports:
  #     - 8080:8080
  
  # product-api:
  #   build: './repos/product-api'
  #   container_name: product-api
  #   environment:
  #     - PORT=8081
  #   ports:
  #     - 8081:8081
  
  # sales-api:
  #   build: './repos/sales-api'
  #   container_name: sales-api
  #   environment:
  #     - PORT=8082
  #   ports:
  #     - 8082:8082

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672